#!groovy

// Generated by IBM TransformationAdvisor
// Mon Jul 22 14:09:13 EDT 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'accmgmtwar'
    mvnCommands = 'clean package'
    test='false'
}